using MEA.Server.DTO.AmCertificate;
using MEA.Server.Entities;

namespace MEA.Server.Mappings;

public static class AmCertificateMappings
{
    public static AmCertificate ToEntity(this CreateAmCertificateDto dto, string companyUserId) => new()
    {
        CertificateRequestId            = dto.CertificateRequestId,
        CompanyUserId                   = companyUserId,
        CreatedAt                       = DateTime.UtcNow,
        ConsignorName                   = dto.ConsignorName,
        ConsignorAddress                = dto.ConsignorAddress,
        ConsignorPostal                 = dto.ConsignorPostal,
        ConsignorTel                    = dto.ConsignorTel,
        CertRefNumber                   = dto.CertRefNumber,
        CertRefNumberA                  = dto.CertRefNumberA,
        CentralCompetentAuthority       = dto.CentralCompetentAuthority,
        LocalCompetentAuthority         = dto.LocalCompetentAuthority,
        ConsigneeName                   = dto.ConsigneeName,
        ConsigneeAddress                = dto.ConsigneeAddress,
        ConsigneePostal                 = dto.ConsigneePostal,
        ConsigneeTel                    = dto.ConsigneeTel,
        Consignee6                      = dto.Consignee6,
        CountryOrigin                   = dto.CountryOrigin,
        CountryOriginISO                = dto.CountryOriginISO,
        RegionOrigin                    = dto.RegionOrigin,
        RegionOriginISO                 = dto.RegionOriginISO,
        CountryDestination              = dto.CountryDestination,
        CountryDestinationISO           = dto.CountryDestinationISO,
        CountryDestination110           = dto.CountryDestination110,
        PlaceOfOriginName               = dto.PlaceOfOriginName,
        PlaceOfOriginAddress            = dto.PlaceOfOriginAddress,
        PlaceOfOriginApprovalNo         = dto.PlaceOfOriginApprovalNo,
        CountryDestination112           = dto.CountryDestination112,
        PlaceOfLoading                  = dto.PlaceOfLoading,
        DateOfDeparture                 = dto.DateOfDeparture,
        TransportAeroPlane              = dto.TransportAeroPlane,
        TransportShip                   = dto.TransportShip,
        TransportRailwayWagon           = dto.TransportRailwayWagon,
        TransportRoadVehicle            = dto.TransportRoadVehicle,
        TransportOther                  = dto.TransportOther,
        TransportId                     = dto.TransportId,
        EntryBIP                        = dto.EntryBIP,
        Field117                        = dto.Field117,
        DescCommon                      = dto.DescCommon,
        HsCode                          = dto.HsCode,
        Quantity                        = dto.Quantity,
        TemperatureAmbient              = dto.TemperatureAmbient,
        TemperatureChilled              = dto.TemperatureChilled,
        TemperatureFrozen               = dto.TemperatureFrozen,
        NumPackages                     = dto.NumPackages,
        ContainerId                     = dto.ContainerId,
        PackagingType                   = dto.PackagingType,
        ForHumanConsumption             = dto.ForHumanConsumption,
        Field126                        = dto.Field126,
        ForImportEU                     = dto.ForImportEU,
        ProcessingEstName               = dto.ProcessingEstName,
        ProcessingEstRegNo              = dto.ProcessingEstRegNo,
        ProcessingEstAddress            = dto.ProcessingEstAddress,
        HealthCertNo                    = dto.HealthCertNo,
        HealthCertNoB                   = dto.HealthCertNoB,
        CertificateNo                   = dto.CertificateNo ?? dto.HealthCertNo ?? dto.CertRefNumber,
        CountryIssuing                  = dto.CountryIssuing,
        CompetentAuthorityExporting     = dto.CompetentAuthorityExporting,
        OrganizationIssuing             = dto.OrganizationIssuing,
        CountryOfTransit                = dto.CountryOfTransit,
        PointOfCrossingBorder           = dto.PointOfCrossingBorder,
        ProductName                     = dto.ProductName,
        ProductionDate                  = dto.ProductionDate,
        NetWeight                       = dto.NetWeight,
        NumberOfSeal                    = dto.NumberOfSeal,
        IdentificationMarks             = dto.IdentificationMarks,
        StorageConditions               = dto.StorageConditions,
        FactoryVessel                   = dto.FactoryVessel,
        ColdStore                       = dto.ColdStore,
        AdministrativeUnit              = dto.AdministrativeUnit,
        PlaceOfIssue                    = dto.PlaceOfIssue,
        DateOfIssue                     = dto.DateOfIssue,
        DateOfAttachment                = dto.DateOfAttachment,
        IdentificationMarksAttachment   = dto.IdentificationMarksAttachment,
        ExportApprovalNumber            = dto.ExportApprovalNumber,
        SignatoryUserId                 = dto.SignatoryUserId,
        SignatoryName                   = dto.SignatoryName,
        Qualification                   = dto.Qualification,
        SignatureDate                   = dto.SignatureDate,
        Stamp                           = dto.Stamp,
        Signature                       = dto.Signature,
        PreExportCertificates = dto.PreExportCertificates.Select(p => new AmPreExportCertificate
        {
            Date                    = p.Date,
            Number                  = p.Number,
            CountryOfOrigin         = p.CountryOfOrigin,
            AdministrativeTerritory = p.AdministrativeTerritory,
            ApprovalNumber          = p.ApprovalNumber,
            ProductNameAndQuantity  = p.ProductNameAndQuantity
        }).ToList(),
        Attachments = dto.Attachments.Select(a => new AmAttachment
        {
            Product       = a.Product,
            NumberOfKgs   = a.NumberOfKgs,
            NumberOfBoxes = a.NumberOfBoxes
        }).ToList()
    };
}

