using MEA.Server.DTO.IdCertificate;
using MEA.Server.Entities;

namespace MEA.Server.Mappings;

public static class IdCertificateMappings
{
    public static IdCertificate ToEntity(this CreateIdCertificateDto dto, string companyUserId) => new()
    {
        CertificateRequestId        = dto.CertificateRequestId,
        CompanyUserId               = companyUserId,
        CreatedAt                   = DateTime.UtcNow,
        NumberNomor                 = dto.NumberNomor,
        ConsignorName               = dto.ConsignorName,
        ConsignorAddress            = dto.ConsignorAddress,
        ConsigneeName               = dto.ConsigneeName,
        ConsigneeAddress            = dto.ConsigneeAddress,
        CompetentAuthority          = dto.CompetentAuthority,
        EstablishmentAquaculture    = dto.EstablishmentAquaculture ?? false,
        EstablishmentProcessing     = dto.EstablishmentProcessing ?? false,
        EstablishmentOther          = dto.EstablishmentOther ?? false,
        EstablishmentName           = dto.EstablishmentName,
        EstablishmentRegNo          = dto.EstablishmentRegNo,
        EstablishmentAddress        = dto.EstablishmentAddress,
        CountryRegionOrigin         = dto.CountryRegionOrigin,
        SourceFarmRaised            = dto.SourceFarmRaised ?? false,
        SourceWildCaught            = dto.SourceWildCaught ?? false,
        PortOfShipment              = dto.PortOfShipment,
        TransportAir                = dto.TransportAir ?? false,
        TransportSea                = dto.TransportSea ?? false,
        TransportRoad               = dto.TransportRoad ?? false,
        CommodityDescription        = dto.CommodityDescription,
        TempAmbient                 = dto.TempAmbient ?? false,
        TempFrozen                  = dto.TempFrozen ?? false,
        TempChilled                 = dto.TempChilled ?? false,
        IntendedHumanConsumption    = dto.IntendedHumanConsumption ?? false,
        IntendedCultureBreeding     = dto.IntendedCultureBreeding ?? false,
        IntendedTrade               = dto.IntendedTrade ?? false,
        IntendedResearch            = dto.IntendedResearch ?? false,
        IntendedFishFeed            = dto.IntendedFishFeed ?? false,
        IntendedExhibition          = dto.IntendedExhibition ?? false,
        IntendedOther               = dto.IntendedOther ?? false,
        TotalPackages               = dto.TotalPackages,
        PackagingType               = dto.PackagingType,
        TotalQuantityKg             = dto.TotalQuantityKg,
        ContainerSealNumber         = dto.ContainerSealNumber,
        PortOfDestination           = dto.PortOfDestination,
        TransportVesselName         = dto.TransportVesselName,
        TransportVoyageNumber       = dto.TransportVoyageNumber,
        DateOfDeparture             = dto.DateOfDeparture,
        TestingLaboratory           = dto.TestingLaboratory,
        LaboratoryAddress           = dto.LaboratoryAddress,
        ApprovingOfficerName        = dto.ApprovingOfficerName,
        TestResultNumber            = dto.TestResultNumber,
        AttestationRefNumber        = dto.AttestationRefNumber,
        AttestFinfish               = dto.AttestFinfish ?? false,
        AttestMollusca              = dto.AttestMollusca ?? false,
        AttestCrustacea             = dto.AttestCrustacea ?? false,
        AttestFisheryProducts       = dto.AttestFisheryProducts ?? false,
        AttestOther                 = dto.AttestOther ?? false,
        AttestClauseA               = dto.AttestClauseA ?? false,
        AttestClauseB               = dto.AttestClauseB ?? false,
        AttestClauseC               = dto.AttestClauseC ?? false,
        AttestClauseCCrustacean     = dto.AttestClauseCCrustacean ?? false,
        AttestClauseCCyprinidae     = dto.AttestClauseCCyprinidae ?? false,
        AttestClauseCTilapia        = dto.AttestClauseCTilapia ?? false,
        AttestClauseCCatfish        = dto.AttestClauseCCatfish ?? false,
        AttestClauseCOtherFish      = dto.AttestClauseCOtherFish ?? false,
        AttestClauseCVisibleSigns   = dto.AttestClauseCVisibleSigns ?? false,
        AttestClauseCPackagedContainers = dto.AttestClauseCPackagedContainers ?? false,
        AttestClauseD               = dto.AttestClauseD ?? false,
        AttestClauseE               = dto.AttestClauseE ?? false,
        AdditionalInformation       = dto.AdditionalInformation,
        SignatoryUserId             = dto.SignatoryUserId,
        SignatoryName               = dto.SignatoryName,
        Qualification               = dto.Qualification,
        CertifiedIssuedAt           = dto.CertifiedIssuedAt,
        CertifiedDate               = dto.CertifiedDate,
        CertifiedPosition           = dto.CertifiedPosition,
        CertifiedPhone              = dto.CertifiedPhone,
        CertifiedFax                = dto.CertifiedFax,
        CertifiedEmail              = dto.CertifiedEmail,
        CertifiedAddress            = dto.CertifiedAddress,
        Products = dto.Products.Select(p => new IdCertificateProduct
        {
            No             = p.No,
            CommonName     = p.CommonName,
            ScientificName = p.ScientificName,
            HsCode         = p.HsCode,
            Quantity       = p.Quantity,
            Unit           = p.Unit
        }).ToList()
    };
}

